### ISSUE TITLE
运行时候异常，中间件捕获不到

### ISSUE THREAD

**Issue by hhaojin** [shenyisyn/goft-gin#1]
![image](https://user-images.githubusercontent.com/31870227/93851502-d4219300-fce2-11ea-8ff6-167b3e8863bd.png)
![image](https://user-images.githubusercontent.com/31870227/93851523-dedc2800-fce2-11ea-9d69-7c87eef91bb9.png)

**Comment by shenyisyn** [comment]
收到。这块没有把错误信息放进去
